/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

/**
 *
 * @author adrian
 */
public class Subpage1 extends javax.swing.JFrame {

    /**
     * Creates new form Subpage1
     */
    public Subpage1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Profil = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Profil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/button_default_profile.png"))); // NOI18N
        Profil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ProfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProfilMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ProfilMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ProfilMouseReleased(evt);
            }
        });
        getContentPane().add(Profil, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.setMaximumSize(new java.awt.Dimension(28, 28));
        exit.setMinimumSize(new java.awt.Dimension(28, 28));
        exit.setPreferredSize(new java.awt.Dimension(28, 28));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        exit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                exitMouseDragged(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(765, 6, -1, -1));

        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 6, 28, 28));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background2.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getXOnScreen();

        this.setLocation(x, y);
    }//GEN-LAST:event_exitMouseDragged

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void ProfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfilMouseEntered
        Profil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/button_hover_profile.png")));
    }//GEN-LAST:event_ProfilMouseEntered

    private void ProfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfilMouseExited
        Profil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/button_default_profile.png")));
    }//GEN-LAST:event_ProfilMouseExited

    private void ProfilMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfilMousePressed
        Profil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/button_pressed_profile.png")));
    }//GEN-LAST:event_ProfilMousePressed

    private void ProfilMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfilMouseReleased
        Profil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/button_default_profile.png")));
    }//GEN-LAST:event_ProfilMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Subpage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Subpage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Subpage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Subpage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Subpage1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Profil;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel minimize;
    // End of variables declaration//GEN-END:variables
}
